/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sankuai_jnicase_JniNativeClassCase */

#ifndef _Included_com_sankuai_jnicase_JniNativeClassCase
#define _Included_com_sankuai_jnicase_JniNativeClassCase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseDefineClass
 * Signature: (Lcom/sankuai/jnicase/CustomClassLoader;[BILjava/lang/Class;)Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseDefineClass
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jclass);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseFindClass
 * Signature: ()Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseFindClass
  (JNIEnv *, jclass);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseNewArray
 * Signature: ()[Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseNewArray
  (JNIEnv *, jclass);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseConvertPersonToAnother
 * Signature: (Lcom/sankuai/jnicase/Person;)Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseConvertPersonToAnother
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseInvokeInName
 * Signature: (Lcom/sankuai/jnicase/Person;)V
 */
JNIEXPORT void JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseInvokeInName
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseCreateGlobalRef
 * Signature: (Lcom/sankuai/jnicase/Person;)Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseCreateGlobalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseCreateLocalRef
 * Signature: (Lcom/sankuai/jnicase/Person;)Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseCreateLocalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseCreateWeakGlobalRef
 * Signature: (Lcom/sankuai/jnicase/Person;)Lcom/sankuai/jnicase/Person;
 */
JNIEXPORT jobject JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseCreateWeakGlobalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sankuai_jnicase_JniNativeClassCase
 * Method:    caseException
 * Signature: (Lcom/sankuai/jnicase/CustomException;)V
 */
JNIEXPORT void JNICALL Java_com_sankuai_jnicase_JniNativeClassCase_caseException
  (JNIEnv *, jclass, jthrowable);

#ifdef __cplusplus
}
#endif
#endif
